Coppel/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from core import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^$', views.index, name='index'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
]

shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^list/$', views.productList.as_view(), name='list'),
    url(r'^list/(?P<category_slug>[-\w]+)/$', views.productList.as_view(), name='list_by_cate'),
    url(r'^detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.productDetail.as_view(), name='detail'),
]

cart/models.py
from django.db import models

# Create your models here.

core/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.db import models
from shop.models import Product
# Create your models here.

class Order(models.Model):
    first_name = models.CharField('Nombre(s)', max_length=150)
    last_name = models.CharField('Apellidos', max_length=150)
    email = models.EmailField()
    postal_code = models.CharField('Código Postal', max_length=15)
    adress = models.CharField('Dirección', max_length=120)
    city = models.CharField('Ciudad', max_length=50)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created_date', )

    def __str__(self):
        return 'Orden {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items')
    product = models.ForeignKey(Product, related_name='order_items')
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

shop/models.py
from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.
class Category(models.Model):
    name = models.CharField('Nombre de categoria', max_length=200, db_index=True)
    slug = models.SlugField('Slug', max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:list_by_cate', args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products')
    name = models.CharField('Nombre', max_length=200, db_index=True)
    slug = models.SlugField('Slug', max_length=200, db_index=True)
    image = models.ImageField('Imagen', upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField('Descripción', blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveSmallIntegerField()
    available = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'), )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:detail', args=[self.id, self.slug])

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

orders/forms.py
from django import forms
from .models import Order, OrderItem

class OrderCreateForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'adress',
                'postal_code', 'city']
        

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
# Create your views here.
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity = cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(reqiest, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity':item['quantity'], 'update':True})
    return render(request, 'cart/detail.html', {'cart':cart})

core/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'core/index.html', {'section':'index'})

orders/views.py
from django.shortcuts import render
from .forms import OrderCreateForm
from .models import Order, OrderItem
from cart.cart import Cart
# Create your views here.

def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order, product=item['item'],
                                        price=item['price'],
                                        quantity=item['quantity'])
            # limpiamos el carrito
            cart.clear()
            return render(request, 'orders/order/created.html', {'order':order})
        else:
            form = OrderCreateForm()
        return render(request, 'orders/order/create.html', {'form':form, 'cart':cart})

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View
from cart.forms import CartAddProductForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from .models import Category, Product
# Create your views here.

class productList(View, LoginRequiredMixin):
    login_url = '/accounts/login/'
    redirect_field_name = 'redirect_to'

    @method_decorator(login_required)
    def get(self, request, category_slug=None):
        category = None
        categories = Category.objects.all()
        products = Product.objects.filter(available=True)
        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            products = products.filter(category=category)
        return render(request, 'shop/product/list.html', {'category': category,
                                                            'categories': categories,
                                                            'products': products,
                                                            'section': 'tienda'})
class productDetail(View):

    def get(self, request, id, slug):
        product = get_object_or_404(Product, id=id, slug=slug, available=True)
        cart_product_form = CartAddProductForm()
        return render(request, 'shop/product/detail.html', {'product': product, 'section':'tienda', 'cart_product_form':cart_product_form})

templates/accounts/logout.html
{% extends 'global/base.html' %}

{% block title %} Cerrar Sesisón {% endblock %}

{% block content %}
  <form method="post" action="/accounts/logout/">
  {% csrf_token %}
  {% if redirect_field_value %}
  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
  {% endif %}
  <button type="submit">Cerrar Sesión</button>
  </form>
{% endblock %}

templates/cart/detail.html
{% extends 'global/base.html' %}
{% load thumbnail %}

{% block title %} Detalle de compra {% endblock title %}

{% block content %}
  <div class="container" style="margin-top:30px;">
    <div class="row">
      <div class="col">
        <h1 style="text-align:center;">Tu carrito de compras</h1>
        <table class="cart table table-bordered">
          <thead class="blue-grey lighten-4">
            <tr>
              <th>Imagen</th>
              <th>Producto</th>
              <th>Cantidad</th>
              <th>Eliminar</th>
              <th>Precio Unitario</th>
              <th>Precio</th>
            </tr>
          </thead>
          <tbody>
            {% for item in cart %}
              {% with product=item.product %}
              <tr>
              <td>
                <a href="{{product.get_absolute_url}}">
                  <img src="{{product.image|thumbnail_url:'coach'}}" alt="{{product.name}}">
                </a>
              </td>
              <td>{{ product.name }}</td>
              <td>
                <form class="" action="{% url 'cart:cart_add' product.id %}" method="post">
                  {{ item.update_quantity_form.quantity }}
                  {{ item.update_quantity_form.update }}
                  <input type="submit" value="Actualizar" class="btn btn-info btn-sm">
                  {% csrf_token %}
                </form>
              </td>
              <td><a href="{% url 'cart:cart_remove' product.id %}" class="btn btn-danger btn-sm">Remover</a></td>
              <td>$ {{ item.price }}</td>
              <td>$ {{ item.total_price }}</td>
              </tr>
              {% endwith %}
            {% endfor %}
            <tr>
              <td>Total</td>
              <td colspan="4"></td>
              <td>$ {{ cart.get_total_price }}</td>
            </tr>
          </tbody>
        </table>
        <p class="text-rigth" style="text-align:right;">
          <a href="{% url 'shop:list' %}" class="btn btn-indigo">Continuar comprando</a>
          <a href="{% url 'orders:order_create' %}" class="btn btn-success">Checkout</a>
        </p>
      </div>
    </div>
  </div>
{% endblock content %}

templates/core/index.html
{% extends 'global/base.html' %}

templates/global/base.html
<!DOCTYPE html>
<html lang="es">
{% load static %}
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.9/css/all.css" integrity="sha384-5SOiIsAziJl6AWe0HWRKTXlfcSHKmYV4RBF18PPJ173Kzn7jzMyFuTtk8JA7QQG1" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/custom.css' %}">
  <title>{% block title %} {% endblock %}</title>
</head>
<body>

  {% include 'global/navbar.html' %}

  {% block content %}
  {% endblock content %}
</body>
<script src="{% static 'js/jquery.min.js' %}" charset="utf-8"></script>
<script src="{% static 'js/popper.min.js' %}" charset="utf-8"></script>
<script src="{% static 'js/bootstrap.min.js' %}" charset="utf-8"></script>
<script src="{% static 'js/mdb.min.js' %}" charset="utf-8"></script>
</html>

templates/global/navbar.html
<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-dark" id="primary-color">

    <!-- Navbar brand -->
    <a class="navbar-brand coppel-logo" id="primary-text-color" href="/">Coppel</a>

    <!-- Collapse button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav" aria-controls="basicExampleNav"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Collapsible content -->
    <div class="navbar-collapse collapse justify-content-between" id="basicExampleNav">

        <!-- Links -->
        <ul class="navbar-nav ml-auto">
            <li {% if section == 'index' %} class="nav-item active navbar-links" {% else %} class="nav-item" {% endif %}>
                <a class="nav-link navbar-links" href="/" id="secondary-text-color">Inicio <span class="fa fa-home fa-lg"></span></a>
            </li>
            <li {% if section == 'tienda' %} class="nav-item active navbar-links" {% else %} class="nav-item" {% endif %}>
                <a class="nav-link navbar-links" href="{% url 'shop:list' %}" id="secondary-text-color">Tienda  <span class="fa fa-shopping-basket fa-lg"></span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link navbar-links" href="#" id="secondary-text-color">Nosotros <span class="fa fa-users fa-lg"></span></a>
            </li>

            <li class="nav-item">
              <a href="{% url 'cart:cart_detail' %}" class="nav-link navbar-links" id="secondary-text-color">
                Mi carrito
                <span class="fa fa-shopping-cart fa-lg">
              </span><span class="badge indigo">
                {% with total_items=cart|length %}
                  {% if cart|length > 0 %}
                    {{ total_items }}
                  {% else %}
                    0
                  {% endif %}
                {% endwith %}
              </span>
            </a>
            </li>
            <!-- Dropdown -->
            <li class="nav-item dropdown">
                <a id="secondary-text-color" class="nav-link dropdown-toggle navbar-links" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Cuenta <span class="fa fa-user fa-lg"></span></a>
                <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
                  {% if not request.user.is_authenticated %}
                    <a class="dropdown-item navbar-links" href="/accounts/login/">Iniciar Sesión</a>
                    <a class="dropdown-item navbar-links" href="#">Registrarse</a>
                  {% else %}
                    <a href="/accounts/logout/" class="dropdown-item navbar-links">Cerrar Sesión</a>
                  {% endif %}
                </div>
            </li>

        </ul>
        <!-- Links -->
</nav>
<!--/.Navbar-->

<style media="screen">
  #primary-color  {
    background-color: rgba(239, 233, 56, 0.8);
  }
  #primary-text-color {
    color: rgb(21, 52, 56);
  }
  #secondary-text-color {
    color: rgb(34, 41, 68);
  }
  .coppel-logo {
    font-size: 24px;
    font-weight: 900;
  }
  .navbar-links {
    font-weight: 400;
  }
</style>

templates/orders/order/create.html
{% extends 'global/base.html' %}

{% block title %} Checkout {% endblock %}

{% block content %}
  <div class="container" style="text-align:center;">
    <div class="row">
      <div class="col">
        <h1>Checkout</h1>
        <div class="order-info">
          <h3>Tu orden</h3>
          <ul>
            {% for item in cart %}
              <li>
                {{ item.quantity }} x {{ item.product.name }}
                <span>$ {{item.total_price}}</span>
              </li>
            {% endfor %}
          </ul>
          <p>Total: ${{ cart.get_total_price }}</p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/shop/product/detail.html
{% extends 'global/base.html' %}
{% load thumbnail %}

{% block title %} {{product.name}} {% endblock %}

{% block content %}
<div class="container" style="margin-top: 25px;">
  <div class="row">
    <div class="col-4">
      <img class="img-fluid" src="{% if product.image %} {{product.image.url}} {% endif %}" alt="">
    </div>
    <div class="col">
      <h1 style="text-align:center;">{{product.name}}</h1>
      <hr>
      <h2><a href="{{product.category.get_absolute_url}}">{{product.category}}</a></h2>
      <h3>$ {{product.price}}</h3>
      <form action="{% url 'cart:cart_add' product.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" name="addCart" class="btn btn-indigo btn-sm" value="Añadir al carrito">
      </form>
      <hr>
      <p>{{product.description}}</p>
      <hr>
    </div>
  </div>
</div>
{% endblock content %}

templates/shop/product/list.html
{% extends 'global/base.html' %}
{% load thumbnail %}

{% block title %}
  {% if category %}
    {{category.name}}
  {% else %}
    Lista de productos
  {% endif %}
{% endblock %}

{% block content %}
  <div class="container" id="cont">
    <div class="row">
      <div class="col-3" id="sidebar">
        <h3 style="text-align:center;">Categorias</h3>
        <ul class="list-group">
          <li {% if not category %} class="selected list-group-item" {% endif %} class="list-group-item">
            <a href="{% url 'shop:list' %}">Todos</a>
          </li>
          {% for c in categories %}
            <li {% if category.slug == c.slug %} class="selected list-group-item" {% endif %} class="list-group-item">
              <a href="{{c.get_absolute_url}}">{{c.name}}</a> <span class="badge badge-primary badge-pill">14</span>
            </li>
          {% endfor %}
        </ul>
      </div>
      <!--Jumbotron-->
      <div class="col">
        {% if products %}
          {% for p in products %}
          <div class="card-deck">
                    <!--Card-->
            <div class="card mb-4">

                <!--Card image-->
                <img class="img-fluid img-thumbnail" src="{% if p.image %} {{p.image|thumbnail_url:'sponsor'}} {% endif %}" alt="{{p.name}}">

                <!--Card content-->
                <div class="card-body">
                    <!--Title-->
                    <h4 class="card-title"><a href="{{p.get_absolute_url}}">{{p.name}}</a></h4>
                    <!--Text-->
                    <p class="card-text">{{p.description|truncatechars:160}}</p>
                    <hr>
                    <p> <h4>$ {{p.price}}</h4></p>
                    <a href="{{p.get_absolute_url}}" class="btn btn-primary">Ver más >></a>
                    {% if request.user.is_authenticated %}
                    <a href="#" class="btn btn-indigo">Agregar al carrito <span class="fa fa-cart-plus fa-lg"></span></a>
                    {% endif %}
                </div>

            </div>
            <br>
            <!--/.Card-->
          </div>
          {% endfor %}
        {% else %}
          <h1>No hay productos.</h1>
        {% endif %}
      </div>
      <!--Jumbotron-->
    </div>
  </div>

<style media="screen">
#cont {
  margin-top: 25px;
}

</style>
{% endblock content %}